NoonPost/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('account.urls')),
    path('', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('profile/', include('profile.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from . import views
from django.urls import path

app_name = 'account'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('verify_code/', views.VerifyCodeView.as_view(), name='verify_code'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('forget/', views.ForgetView.as_view(), name='forget'),
    path('forget_otp/', views.ForgetOTPVerifyView.as_view(), name='forget_otp'),
    path('reset_password/', views.ResetPasswordView.as_view(), name='reset_password'),
    path('enter_otp/', views.EnterOTPView.as_view(), name='enter_otp'),
    path('enter_otp_verify/', views.EnterOTPVerifyView.as_view(), name='enter_otp_verify'),
    path('resend_otp/', views.ResendOTPView.as_view(), name='resend_otp'),
]

blog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.home, name='home'),
    path('articles/', views.articles_list, name='article_list'),
    re_path(r'detail/(?P<slug>[-\w]+)/', views.article_detail, name='article_detail'),
    re_path(r'category/(?P<slug>[-\w]+)/', views.category_article, name='category_article'),
    re_path(r'tag/(?P<slug>[-\w]+)/', views.tag_article, name='tag_article'),
    path('author/<int:author_id>/', views.author_detail, name='author_detail'),
    path('search/', views.search, name='search_article'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('subscribe/', views.subscribe, name='subscribe'),
    re_path(r'like/(?P<slug>[-\w]+)/', views.LikeView.as_view(), name='like'),
]

profile/urls.py
from . import views
from django.urls import path

app_name = 'profile'

urlpatterns = [
    path('dashboard/', views.ProfileDashboard.as_view(), name='dashboard'),
    path('favorite/', views.ProfileFavorites.as_view(), name='favorite'),
    path('recent/', views.ProfileRecent.as_view(), name='recent'),
    path('edit/', views.ProfileEdit.as_view(), name='edit'),
    path('new_article/', views.ArticleCreateView.as_view(), name='new_article'),
    path('update_full_name/', views.UpdateFullName.as_view(), name='update_full_name'),
    path('update_phone/', views.UpdatePhone.as_view(), name='update_phone'),
    path('update_email/', views.UpdateEmail.as_view(), name='update_email'),
    path('update_image/', views.UpdateImage.as_view(), name='update_image'),
    path('update_bio/', views.UpdateBio.as_view(), name='update_bio'),
    path('change_password/', views.ChangePassword.as_view(), name='change_password'),
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="fa">
<head>
    <!-- Meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- favicon -->
    <link rel="icon" sizes="16x16" href="{% static 'assets/img/favicon.png' %}">

    <!-- Title -->
    <title>{% block title %}{% endblock %}</title>

    <!-- CSS Plugins -->
    <link rel="stylesheet" href="{% static 'assets/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/elegant-font-icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.css' %}">

    <!-- main style -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">
</head>

<body class="rtl">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg fixed-top">
        <div class="container-fluid">
            <!--logo-->
            <div class="logo">
                <a href="{% url 'blog:home' %}">
                    <img src="{% static 'assets/img/logo-dark.png' %}" alt="" class="logo-dark">
                    <img src="{% static 'assets/img/logo-white.png' %}" alt="" class="logo-white">
                </a>
            </div>
            <!--/-->

            <!--navbar-collapse-->
            <div class="collapse navbar-collapse" id="main_nav">
                <ul class="navbar-nav ml-auto mr-auto">
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'home' %}active{% endif %}" href="{% url 'blog:home' %}">صفحه اصلی</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'article_list' %}active{% endif %}" href="{% url 'blog:article_list' %}">مقالات</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'about' %}active{% endif %}" href="{% url 'blog:about' %}">درباره ما</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'contact' %}active{% endif %}" href="{% url 'blog:contact' %}">ارتباط با ما</a>
                    </li>

                    <li class="nav-item">
                    {% if request.user.is_authenticated %}
                        {% if request.user.image %}
                            <a class="nav-link" href="{% url 'ProfileApp:dashboard' %}">
                                <img src="{{ request.user.image.url }}" style="width: 30px;height: 30px;border-radius: 30px" alt="{{ request.user.full_name }}">
                            </a>
                        {% else %}
                            <a class="nav-link" href="{% url 'profile:dashboard' %}">
                                <img src="{% static 'assets/img/default_profile_image.png' %}" style="width: 30px;height: 30px;border-radius: 30px" alt="{{ request.user.full_name }}">
                            </a>
                        {% endif %}
                    {% else %}
                        <a class="nav-link " href="{% url 'account:register' %}">ثبت نام / ورود</a>
                    {% endif %}
                    </li>

                </ul>
            </div>
            <!--/-->

            <!--navbar-right-->
            <div class="navbar-right ml-auto">
                <div class="theme-switch-wrapper">
                    <label class="theme-switch" for="checkbox">
                        <input type="checkbox" id="checkbox" />
                        <div class="slider round"></div>
                    </label>
                </div>
                <div class="social-icones">
                    <ul class="list-inline">
                        <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                        <li>
                            <a href="#">
                                <i class="fab fa-instagram"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fab fa-twitter"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fab fa-youtube"></i>
                            </a>
                        </li>
                    </ul>
                </div>

                <div class="search-icon">
                    <i class="icon_search"></i>
                </div>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main_nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </div>
    </nav>
    <!--/-->

    {% block content %} {% endblock %}

    <!--newslettre-->
    <section class="newslettre">
        <div class="container-fluid">
            <div class="newslettre-width text-center">
                <div class="newslettre-info">
                    <h5>عضویت در خبرنامه</h5>
                    <p> رایگان ثبت نام کنید و اولین نفری باشید که از پست های جدید مطلع می شوید. </p>
                </div>
                <form action="{% url 'blog:subscribe' %}" method="post" class="newslettre-form">
                    {% csrf_token %}
                    <div class="form-flex">
                        <div class="form-group">
                            <input type="email" name="email" id="email" class="form-control" placeholder="آدرس ایمیل" required="required">
                        </div>
                        <button class="submit-btn" type="submit">عضویت</button>
                    </div>
                </form>
            </div>
        </div>
    </section>

    <!--Search-form-->
    <div class="search">
        <div class="container-fluid">
            <div class="search-width  text-center">
                <button type="button" class="close">
                    <i class="icon_close"></i>
                </button>
                <form class="search-form" method="get" action="{% url 'blog:search_article' %}">
                    <input type="search" name="search" value="" placeholder="مقاله مورد نظرت رو جستجو کن">
                    <button type="submit" class="search-btn">جستجو</button>
                </form>
            </div>
        </div>
    </div>
    <!--/-->


    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'assets/js/jquery-3.5.0.min.js' %}"></script>
    <script src="{% static 'assets/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>

    <!-- JS Plugins  -->
    <script src="{% static 'assets/js/ajax-contact.js' %}"></script>
    <script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/js/switch.js' %}"></script>

    <!-- JS main  -->
    <script src="{% static 'assets/js/main.js' %}"></script>
</body>


</html>